services:
  - type: web
    name: library-management-system
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString

databases:
  - name: library-db
    databaseName: library_management
    user: library_user
    region: oregon
    plan: free
